name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox] # Define the browsers to run tests on
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: npm start &
        env:
          PORT: 3000
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          record: true
          parallel: true
          browser: ${{ matrix.browser }} # Run tests in the specified browser
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
