name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: npm start &
        env:
          PORT: 3000

      - name: Run Cypress Tests
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
            npm run test:chrome
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            npm run test:firefox
          fi
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}